database:
  driverClass: org.postgresql.Driver
  user: morpheus
  password: findneo
  url: jdbc:postgresql://127.0.0.1/sre-lab

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.jdbc.batch_sze: 100
    hibernate.order_inserts: true
    hibernate.order_updates: true

  maxWaitForConnection: 1s
  validationQuery: "/* Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
