apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0
        max_path_tag_length: 256
        openCensusAgent:
          address: "http://signoz-otel-collector.platform.svc.cluster.local:4317"
        custom_tags:
          clusterID:
            environment:
              name: ISTIO_META_CLUSTER_ID
