name: Users API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: users-api

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...